services:
  map_back:
    container_name: 'map_back'
    build:
      context: .
    volumes:
      - static-data:/app/src/static/images
    #ports:
    #  - "8000:8000"
    networks:
      - MapNetwork
    env_file:
      - .env
    depends_on:
      map_db:
        condition: service_healthy
      map_cache:
        condition: service_healthy

  map_db:
    image: postgres:16-alpine
    container_name: 'map_db'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "6432:5432"
    volumes:
      - pg-map-data:/var/lib/postgresql/data
    networks:
      - MapNetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d MapApp" ]
      interval: 10s
      timeout: 5s
      retries: 5

  map_cache:
    image: redis:7-alpine
    container_name: 'map_cache'
    ports:
      - "7379:6379"
    networks:
      - MapNetwork
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

  map_celery_worker:
    container_name: 'map_celery_worker'
    build:
      context: .
    volumes:
      - static-data:/app/src/static/images
    networks:
      - MapNetwork
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO"
    depends_on:
      - map_db
      - map_cache

  map_nginx:
    image: nginx:alpine
    container_name: 'map_nginx'
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - MapNetwork
    depends_on:
      map_back:
        condition: service_started

volumes:
  pg-map-data:
  static-data:

networks:
  MapNetwork:
    external: true